# Generated by Django 4.2.5 on 2023-09-24 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weddingplanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='wedding',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='weddingplanner.wedding'),
        ),
    ]
